debug: true
web:
  host: 127.0.0.1
  port: 8000

sentry:
  dsn:
  env: dev

database:
  host: localhost
  port: 5432
  user: pupupu
  password: 123456
  database: kts_project
admin:
  email: "pupupuadmin@gmail.com"
  password: "ultra_super_secure_password"
store: {}
