"""changed ChatSession

Revision ID: 1690856a666b
Revises: 6ed76ced9da9
Create Date: 2025-04-21 03:59:45.550587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1690856a666b'
down_revision: Union[str, None] = '6ed76ced9da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('used_theme_questions', sa.JSON(), nullable=True))
    op.add_column('chat_sessions', sa.Column('game_themes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'game_themes')
    op.drop_column('chat_sessions', 'used_theme_questions')
    # ### end Alembic commands ###
