"""initial

Revision ID: 3fbb77b2c3a8
Revises: 
Create Date: 2025-04-15 21:32:03.753180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbb77b2c3a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat_sessions',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('players', sa.JSON(), nullable=True),
    sa.Column('current_game_state', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('themes',
    sa.Column('_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('theme_name')
    )
    op.create_table('users',
    sa.Column('_id', sa.BigInteger(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('total_wins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes._id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('users')
    op.drop_table('themes')
    op.drop_table('chat_sessions')
    op.drop_table('admins')
    # ### end Alembic commands ###
