"""add_current_theme_to_chat_sessions

Revision ID: 6ed76ced9da9
Revises: 3fbb77b2c3a8
Create Date: 2025-04-17 16:55:00.941838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed76ced9da9'
down_revision: Union[str, None] = '3fbb77b2c3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('current_theme', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'current_theme')
    # ### end Alembic commands ###
