name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install ruff
        run: pip install ruff==0.4.2
      - run: ruff format --check && ruff check --no-fix

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kts-final-project-bot:latest
            ghcr.io/${{ github.repository_owner }}/kts-final-project-bot:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/kts-final-project-bot:latest
            docker stop kts-bot || true
            docker rm kts-bot || true
            docker run -d \
              --name kts-bot \
              --restart unless-stopped \
              -p 8000:8000 \
              -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
              -e DATABASE_HOST=${{ secrets.DB_HOST }} \
              -e DATABASE_PORT=${{ secrets.DB_PORT }} \
              -e DATABASE_USER=${{ secrets.DB_USER }} \
              -e DATABASE_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DATABASE_NAME=${{ secrets.DB_NAME }} \
              ghcr.io/${{ github.repository_owner }}/kts-final-project-bot:latest